version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: telegram_ai_bot
    ports:
      - "8443:8443"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./certs/fullchain.pem:/etc/letsencrypt/live/domain.example.com/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/letsencrypt/live/domain.example.com/privkey.pem:ro
    restart: unless-stopped
