version: "3.8"

services:
  cybermentorbot:
    build: .
    container_name: CyberMentorBot
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /etc/letsencrypt/live/info.lorenzocammarano.me:/certs:ro
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - OVH_API_KEY=${OVH_API_KEY}
      - OVH_API_URL=${OVH_API_URL}
      - SSL_CERT_PATH=/certs/fullchain.pem
      - SSL_KEY_PATH=/certs/privkey.pem